const artists = {
  thomas: {
    name: "THOMAS",
    track1: "YOUNG, WILD & FREE",
    album1: "Mac and Devin Go to High School",
    release1: "2011",
    track2: "BLACK AND YELLOW",
    album2: "ROLLING PAPERS",
    release2: "2011",
    track3: "STILL D.R.E",
    album3: "'2001'",
    release3: "1999",
    image: "/images/thomas.png",
  },
  juliette: {
    name: "JULIETTE",
    track1: "LE TEMPS",
    album1: "Liens du 100",
    release1: "2022",
    track2: "BOLIDE ALLEMAND",
    album2: "Liens du 100",
    release2: "2022",
    track3: "POUR ELLE",
    album3: "A la vie a la mort",
    release3: "2024",
    image: "",
  },
  maxime: {
    name: "MAXIME",
    track1: "",
    album1: "",
    release1: "",
    track2: "",
    album2: "",
    release2: "",
    track3: "",
    album3: "",
    release3: "",
    image: "",
  },
  romain: {
    name: "ROMAIN",
    track1: "",
    album1: "",
    release1: "",
    track2: "",
    album2: "",
    release2: "",
    track3: "",
    album3: "",
    release3: "",
    image: "",
  },

  joel: {
    name: "JOEL",
    track1: "",
    album1: "",
    release1: "",
    track2: "",
    album2: "",
    release2: "",
    track3: "",
    album3: "",
    release3: "",
    image: "",
  },

  teddy: {
    name: "TEDDY",
    track1: "",
    album1: "",
    release1: "",
    track2: "",
    album2: "",
    release2: "",
    track3: "",
    album3: "",
    release3: "",
    image: "",
  },
  cecile: {
    name: "CECILE",
    track1: "",
    album1: "",
    release1: "",
    track2: "",
    album2: "",
    release2: "",
    track3: "",
    album3: "",
    release3: "",
    image: "",
  },
};

function artistUpdate() {
  const nameToUpdate = document.getElementById("artistName");
  nameToUpdate.innerHTML = artists.juliette.name;
}

const cardJuliette = document.getElementById("card-juliette");
cardJuliette.addEventListener("click", artistUpdate);
