const artists = [
  {
    thomas: [
      {
        name: "THOMAS",
        track1: "YOUNG, WILD & FREE",
        album1: "Mac and Devin Go to High School",
        release1: "2011",
        track2: "",
        album2: "",
        release2: "",
        track3: "",
        album3: "",
        release3: "",
        image: "/images/thomas.png",
      },
    ],
    juliette: [
      {
        name: "",
        track1: "",
        album1: "",
        release1: "",
        track2: "",
        album2: "",
        release2: "",
        track3: "",
        album3: "",
        release3: "",
        image: "",
      },
    ],
    maxime: [
      {
        name: "",
        track1: "",
        album1: "",
        release1: "",
        track2: "",
        album2: "",
        release2: "",
        track3: "",
        album3: "",
        release3: "",
        image: "",
      },
    ],
    romain: [
      {
        name: "",
        track1: "",
        album1: "",
        release1: "",
        track2: "",
        album2: "",
        release2: "",
        track3: "",
        album3: "",
        release3: "",
        image: "",
      },
    ],
    joel: [
      {
        name: "",
        track1: "",
        album1: "",
        release1: "",
        track2: "",
        album2: "",
        release2: "",
        track3: "",
        album3: "",
        release3: "",
        image: "",
      },
    ],
    teddy: [
      {
        name: "",
        track1: "",
        album1: "",
        release1: "",
        track2: "",
        album2: "",
        release2: "",
        track3: "",
        album3: "",
        release3: "",
        image: "",
      },
    ],
    cecile: [
      {
        name: "",
        track1: "",
        album1: "",
        release1: "",
        track2: "",
        album2: "",
        release2: "",
        track3: "",
        album3: "",
        release3: "",
        image: "",
      },
    ],
  },
];
